# Generated by Django 4.2.1 on 2023-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0003_rename_company_id_companybranch_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybranch',
            name='branch_CNPJ',
            field=models.CharField(default=31565104002030, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
